BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
	DBMS_OUTPUT.PUT('HOW ARE YOU?');
	DBMS_OUTPUT.PUT_LINE(' BYE');
END;

DECLARE
	NUM NUMBER := 15;
BEGIN
	DBMS_OUTPUT.PUT_LINE('VALUE OF NUMBER = '||NUM);
END;

-- WRITE A PROGRAM TO SWAP VALUES OF TWO VARIABLES USING THIRD VARIABLE
DECLARE
	NUM1 NUMBER := 10;
	NUM2 NUMBER := 20;
	NUM3 NUMBER;
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF NUM1 BEFORE SWAPPING = '||NUM1);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF NUM2 BEFORE SWAPPING = '||NUM2);
	NUM3 := NUM1;
	NUM1 := NUM2;
	NUM2 := NUM3;
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF NUM1 AFTER SWAPPING = '||NUM1);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF NUM2 AFTER SWAPPING = '||NUM2);
END;

-- WRITE A PROGRAM TO MAKE BASIC CALCULATOR
DECLARE 
	NUM1 NUMBER := 10;
	NUM2 NUMBER := 20;
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE ADDITION IS = '|| (NUM1 + NUM2));
	DBMS_OUTPUT.PUT_LINE('THE SUBTRACTION IS = '|| (NUM1 - NUM2));
	DBMS_OUTPUT.PUT_LINE('THE MULTIPLICATION IS = '|| (NUM1 * NUM2));
	DBMS_OUTPUT.PUT_LINE('THE DIVISION IS = '|| (NUM1 / NUM2));
	DBMS_OUTPUT.PUT_LINE('THE REMAINDER IS = '|| MOD(NUM1,NUM2));
END;

-- BLOCKS
DECLARE -- FIRST BLOCK STARTS
	X NUMBER := 10;
BEGIN
	DECLARE -- SECOND BLOCK STARTS
		Y NUMBER := 20;
	BEGIN
		DECLARE -- THIRD BLOCK STARTS
			Z NUMBER := 30;
		BEGIN
            DBMS_OUTPUT.PUT_LINE('THIRD BLOCK := ');
			DBMS_OUTPUT.PUT_LINE('VALUE OF X = '||X);
			DBMS_OUTPUT.PUT_LINE('VALUE OF Y = '||Y);
			DBMS_OUTPUT.PUT_LINE('VALUE OF Z = '||Z);
		END; -- THIRD BLOCK ENDS
		DBMS_OUTPUT.PUT_LINE('SECOND BLOCK := ');
		DBMS_OUTPUT.PUT_LINE('VALUE OF X = '||X);
		DBMS_OUTPUT.PUT_LINE('VALUE OF Y = '||Y);
	END; -- SECOND BLOCK ENDS
	DBMS_OUTPUT.PUT_LINE('FIRST BLOCK := ');
	DBMS_OUTPUT.PUT_LINE('VALUE OF X = '||X);
END; -- FIRST BLOCK ENDS

-- WRITE A PROGRAM TO CHECK WHETHER NUMBER IS ODD OR EVEN
DECLARE
	NUM NUMBER := 8;
BEGIN
	IF MOD(NUM,2) = 0 THEN
		DBMS_OUTPUT.PUT_LINE(NUM||' IS AN EVEN NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM||' IS AN ODD NUMBER');
	END IF;
END;